import type { Metadata } from 'next';
import { IBM_Plex_Mono, Barlow } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/shared/theme/theme-provider';

const ibmMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--font-ibm-mono',
});
const barlow = Barlow({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] as const,
  variable: '--font-barlow',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR'>
      <body className={`${barlow.className} ${ibmMono.variable} antialiased`}>
        <ThemeProvider name='light'>{children}</ThemeProvider>
      </body>
    </html>
  );
}
