import type { Metadata } from 'next';
import { IBM_Plex_Mono, Inter_Tight } from 'next/font/google';
import './globals.css';

const ibmMono = IBM_Plex_Mono({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--font-ibm-mono',
});
const interTight = Inter_Tight({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'] as const,
  variable: '--font-inter-tight',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR'>
      <body className={`${interTight.variable} ${ibmMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
